### ISSUE TITLE
Please do not provide a google drive link to ffplay

### ISSUE THREAD

**Issue by moritztim** [CaffeinatedDragonWare/WindowsHandheldMod#2]
It just really makes it smell like a virus. (I did check it and it seems to be fine)
Just provide the official download link (which I can't get atm cuz [ffmpeg.org](https://ffmpeg.org) is down

**Comment by moritztim** [comment]
not to mention it won't be up to date unless you re upload after every ffmpeg release

**Comment by moritztim** [comment]
I just found out that ffmpeg doesn't supply builds but I found an often referenced source. Added it to the pr.

**Comment by CaffeinatedDragonWare** [comment]
Makes sense. I was linking to their official site before but a few months ago, they released a number of broken builds. I re-added the link to the official ffplay download page and kept the google drive link as a backup.

**Comment by moritztim** [comment]
In my pull request I just went ahead and linked to the gyan.dev download, which is what's listed on the website as well as in winget's database. I also mentioned that you can get it through winget

**Comment by CaffeinatedDragonWare** [comment]
I merged your pull request. Thank you for cleaning up the formatting on my readme!
