### ISSUE TITLE
`-gamepadui` not needed

### ISSUE THREAD

**Issue by moritztim** [CaffeinatedDragonWare/WindowsHandheldMod#7]
This doesn't do anything for me. If I start steam with this while the setting to start steam in BPM is disabled, it doesn't do anything.
What I did:
- turn the steam setting off
- exit/shut down steam
- start steam with this argument

It did not start in BPM. And when I did the same with the setting on and without the argument it did start in BPM. So it seems like this argument doesn't change anything

**Comment by CaffeinatedDragonWare** [comment]
Interesting, it works for me if I add this argument to my Desktop shortcut for example. I have the start steam in BPM setting disabled in my settings as well but when using that argument, it does launch in BPM. 

I wonder, do you have steam setup to start automatically on when Windows boots? Perhaps, that could be causing issues.

**Comment by moritztim** [comment]
> I wonder, do you have steam setup to start automatically on when Windows boots

No, and for this test I just launched it from the start menu.
