### ISSUE TITLE
Black Screen after Reboot (no shell)

### ISSUE THREAD

**Issue by moritztim** [CaffeinatedDragonWare/WindowsHandheldMod#8]
If you forgot to place a startup script into the videos folder, you will be faced with this message and a black screen:
![error message](https://github.com/user-attachments/assets/c3079bb9-fd8e-4fce-bc79-f229d7e21873)
1. Don't panic
2. Press `ctrl`+`shift`+`esc`
3. Click on `Run new Task`
4. Type `C:\Windows\explorer.exe`
5. Check the box and press ok

![image](https://github.com/user-attachments/assets/5a762c85-d82a-428b-a3f2-43254d4494b6)

6. Fix the missing file before your next reboot

**Comment by CaffeinatedDragonWare** [comment]
Thanks! I added your changes.
